name = "bastard-feedback-api"
main = "src/index.ts"
compatibility_date = "2026-04-01"

[[d1_databases]]
binding = "DB"
database_name = "bastard-feedback"
database_id = "c5c69571-302b-4b03-add4-d9afc0b7007e"
